FROM nginx:1.25-alpine

COPY index.html main.js styles.css /usr/share/nginx/html/
COPY images/ /usr/share/nginx/html/images/
COPY files/ /usr/share/nginx/html/files/
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
